# Generated by Django 4.1.5 on 2023-01-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_cart_id_alter_cart_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='uuid',
            new_name='id',
        ),
    ]
