repos:
  - repo: local
    hooks:
      - id: system
        name: black
        entry: black
        types: [python]
        pass_filenames: true
        language: system

  - repo: local
    hooks:
      - id: system
        name: isort
        entry: isort
        types: [python]
        pass_filenames: true
        language: system
